name: Refresh script

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose your desired Python version

    - name: Run Python Script
      run: python refresh.py --empty
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.BOT_SECRET }}
        message: 'chore: empty reservations'
