name: refresh-job

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose your desired Python version

    - name: Run Python Script
      run: IN_CI=1 python refresher.py
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: 'chore: refresh'
