name: Refresh job

on:
  schedule:
    - cron: '1,6,11,16,21,26,31,36,41,46,51,56 6-21 * * *'

jobs:
  run-script:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose your desired Python version

    - name: Run Python Script
      run: IN_CI=1 python refresher.py
      
    - name: Push to repo
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.PUSH_SECRET }}
        branch: main
        unprotect_reviews: true
