name: Reserve

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Vreme za koje rezervisete. Proverite u README.md koja su slobodna vremena. Format: HH:MM'
        required: true
      players:
        description: 'Igraci koji ce igrati ili neka poruka'
        required: false
        default: 'Neki igraci'

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose your desired Python version

    - name: Run Python Script
      run: IN_CI=1 python reserver.py ${{ github.event.inputs.start }} ${{ github.actor }} '${{ github.event.inputs.players }}'
      
    - name: Push to repo
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.PUSH_SECRET }}
        branch: main
        unprotect_reviews: true

